# Generated by Django 4.1.1 on 2022-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Auditor', 'Auditor'), ('Subcontractor', 'Subcontractor')], default='Admin', max_length=50, null=True),
        ),
    ]
